import type { StockItem } from "./api";

export const mockStockItems: StockItem[] = [
  {
    id: "stock_1",
    name: "Lavender Essential Oil",
    sku: "EO-LAV-100",
    category: "Essential Oils",
    location: "treatment",
    quantity: 15,
    minQuantity: 10,
    unit: "bottles",
    cost: 24.99,
    retailPrice: 49.99,
    supplier: "Aromatics International",
    notes: "Premium grade, therapeutic quality",
    lastRestocked: "2024-11-01T10:00:00Z",
  },
  {
    id: "stock_2",
    name: "Massage Oil - Unscented",
    sku: "MO-UNS-500",
    category: "Massage Oils",
    location: "treatment",
    quantity: 8,
    minQuantity: 12,
    unit: "bottles",
    cost: 18.5,
    retailPrice: 35.0,
    supplier: "Professional Spa Supplies",
    notes: "Low stock - reorder soon",
    lastRestocked: "2024-10-15T14:30:00Z",
  },
  {
    id: "stock_3",
    name: "Facial Cleanser - Organic",
    sku: "FC-ORG-250",
    category: "Skincare",
    location: "retail",
    quantity: 24,
    minQuantity: 15,
    unit: "bottles",
    cost: 12.0,
    retailPrice: 28.99,
    supplier: "Green Beauty Co",
    notes: "Popular retail item",
    lastRestocked: "2024-11-10T09:00:00Z",
  },
  {
    id: "stock_4",
    name: "Hot Stones Set",
    sku: "HS-SET-01",
    category: "Equipment",
    location: "storage",
    quantity: 3,
    minQuantity: 2,
    unit: "sets",
    cost: 85.0,
    supplier: "Spa Equipment Pro",
    notes: "Backup sets for maintenance",
    lastRestocked: "2024-08-20T11:00:00Z",
  },
  {
    id: "stock_5",
    name: "Disposable Face Masks",
    sku: "DFM-100",
    category: "Disposables",
    location: "treatment",
    quantity: 145,
    minQuantity: 100,
    unit: "boxes",
    cost: 8.99,
    supplier: "Medical Supplies Direct",
    notes: "Each box contains 50 masks",
    lastRestocked: "2024-11-12T16:00:00Z",
  },
  {
    id: "stock_6",
    name: "Peppermint Essential Oil",
    sku: "EO-PEP-100",
    category: "Essential Oils",
    location: "treatment",
    quantity: 12,
    minQuantity: 8,
    unit: "bottles",
    cost: 19.99,
    retailPrice: 39.99,
    supplier: "Aromatics International",
    notes: "Great for headache relief treatments",
    lastRestocked: "2024-11-01T10:00:00Z",
  },
  {
    id: "stock_7",
    name: "Exfoliating Body Scrub",
    sku: "BS-EXF-500",
    category: "Skincare",
    location: "retail",
    quantity: 18,
    minQuantity: 12,
    unit: "jars",
    cost: 15.5,
    retailPrice: 34.99,
    supplier: "Spa Essentials Ltd",
    notes: "Coconut & sea salt blend",
    lastRestocked: "2024-10-28T13:00:00Z",
  },
  {
    id: "stock_8",
    name: "Massage Table Sheets",
    sku: "MTS-WHT-10",
    category: "Linens",
    location: "storage",
    quantity: 45,
    minQuantity: 30,
    unit: "sets",
    cost: 12.0,
    supplier: "Linen Wholesale Pro",
    notes: "White cotton blend, fitted",
    lastRestocked: "2024-11-05T10:30:00Z",
  },
  {
    id: "stock_9",
    name: "Aromatherapy Diffuser",
    sku: "AD-ULT-01",
    category: "Equipment",
    location: "retail",
    quantity: 6,
    minQuantity: 5,
    unit: "units",
    cost: 45.0,
    retailPrice: 89.99,
    supplier: "Wellness Tech",
    notes: "Ultrasonic model with LED lights",
    lastRestocked: "2024-11-08T14:00:00Z",
  },
  {
    id: "stock_10",
    name: "Facial Toner - Rose",
    sku: "FT-ROS-250",
    category: "Skincare",
    location: "treatment",
    quantity: 14,
    minQuantity: 10,
    unit: "bottles",
    cost: 10.5,
    retailPrice: 24.99,
    supplier: "Green Beauty Co",
    notes: "Bestseller for facials",
    lastRestocked: "2024-11-10T09:00:00Z",
  },
  {
    id: "stock_11",
    name: "Tea Tree Essential Oil",
    sku: "EO-TEA-100",
    category: "Essential Oils",
    location: "treatment",
    quantity: 9,
    minQuantity: 8,
    unit: "bottles",
    cost: 16.99,
    retailPrice: 34.99,
    supplier: "Aromatics International",
    notes: "Antibacterial properties",
    lastRestocked: "2024-11-01T10:00:00Z",
  },
  {
    id: "stock_12",
    name: "Hand Cream - Lavender",
    sku: "HC-LAV-100",
    category: "Skincare",
    location: "retail",
    quantity: 32,
    minQuantity: 20,
    unit: "tubes",
    cost: 6.5,
    retailPrice: 16.99,
    supplier: "Spa Essentials Ltd",
    notes: "Popular gift item",
    lastRestocked: "2024-11-13T11:00:00Z",
  },
  {
    id: "stock_13",
    name: "Massage Oil - Warming",
    sku: "MO-WAR-500",
    category: "Massage Oils",
    location: "treatment",
    quantity: 5,
    minQuantity: 8,
    unit: "bottles",
    cost: 22.0,
    retailPrice: 42.0,
    supplier: "Professional Spa Supplies",
    notes: "LOW STOCK - Contains ginger & cinnamon",
    lastRestocked: "2024-10-15T14:30:00Z",
  },
  {
    id: "stock_14",
    name: "Paraffin Wax",
    sku: "PW-UNS-5KG",
    category: "Treatment Supplies",
    location: "storage",
    quantity: 8,
    minQuantity: 5,
    unit: "blocks",
    cost: 28.0,
    supplier: "Spa Equipment Pro",
    notes: "Unscented, 5kg blocks",
    lastRestocked: "2024-10-22T15:00:00Z",
  },
  {
    id: "stock_15",
    name: "Eucalyptus Essential Oil",
    sku: "EO-EUC-100",
    category: "Essential Oils",
    location: "treatment",
    quantity: 11,
    minQuantity: 8,
    unit: "bottles",
    cost: 18.99,
    retailPrice: 37.99,
    supplier: "Aromatics International",
    notes: "Respiratory benefits",
    lastRestocked: "2024-11-01T10:00:00Z",
  },
  {
    id: "stock_16",
    name: "Disposable Headbands",
    sku: "DH-SPA-50",
    category: "Disposables",
    location: "treatment",
    quantity: 78,
    minQuantity: 50,
    unit: "packs",
    cost: 4.99,
    supplier: "Medical Supplies Direct",
    notes: "Pack of 50, soft velour",
    lastRestocked: "2024-11-07T12:00:00Z",
  },
  {
    id: "stock_17",
    name: "Body Butter - Shea",
    sku: "BB-SHE-250",
    category: "Skincare",
    location: "retail",
    quantity: 21,
    minQuantity: 15,
    unit: "jars",
    cost: 14.0,
    retailPrice: 32.99,
    supplier: "Green Beauty Co",
    notes: "Whipped texture, very popular",
    lastRestocked: "2024-11-10T09:00:00Z",
  },
  {
    id: "stock_18",
    name: "Massage Stone Warmer",
    sku: "MSW-18L",
    category: "Equipment",
    location: "storage",
    quantity: 2,
    minQuantity: 1,
    unit: "units",
    cost: 175.0,
    supplier: "Spa Equipment Pro",
    notes: "18L capacity, digital display",
    lastRestocked: "2024-09-15T10:00:00Z",
  },
  {
    id: "stock_19",
    name: "Facial Serum - Vitamin C",
    sku: "FS-VTC-30",
    category: "Skincare",
    location: "retail",
    quantity: 16,
    minQuantity: 12,
    unit: "bottles",
    cost: 22.5,
    retailPrice: 54.99,
    supplier: "Green Beauty Co",
    notes: "Premium product, high margin",
    lastRestocked: "2024-11-10T09:00:00Z",
  },
  {
    id: "stock_20",
    name: "Massage Oil - Cooling",
    sku: "MO-COL-500",
    category: "Massage Oils",
    location: "treatment",
    quantity: 10,
    minQuantity: 8,
    unit: "bottles",
    cost: 20.0,
    retailPrice: 40.0,
    supplier: "Professional Spa Supplies",
    notes: "Menthol & eucalyptus blend",
    lastRestocked: "2024-10-15T14:30:00Z",
  },
  {
    id: "stock_21",
    name: "Towel Warmers - Small",
    sku: "TW-SM-12",
    category: "Equipment",
    location: "storage",
    quantity: 4,
    minQuantity: 2,
    unit: "units",
    cost: 95.0,
    supplier: "Spa Equipment Pro",
    notes: "12L capacity",
    lastRestocked: "2024-08-30T11:00:00Z",
  },
  {
    id: "stock_22",
    name: "Clay Mask - Detox",
    sku: "CM-DET-250",
    category: "Skincare",
    location: "treatment",
    quantity: 7,
    minQuantity: 10,
    unit: "jars",
    cost: 16.0,
    retailPrice: 36.99,
    supplier: "Spa Essentials Ltd",
    notes: "LOW STOCK - Activated charcoal",
    lastRestocked: "2024-10-20T14:00:00Z",
  },
  {
    id: "stock_23",
    name: "Sandalwood Essential Oil",
    sku: "EO-SAN-100",
    category: "Essential Oils",
    location: "storage",
    quantity: 6,
    minQuantity: 5,
    unit: "bottles",
    cost: 34.99,
    retailPrice: 69.99,
    supplier: "Aromatics International",
    notes: "Premium grade, expensive",
    lastRestocked: "2024-09-10T10:00:00Z",
  },
  {
    id: "stock_24",
    name: "Nail File Sets",
    sku: "NF-SET-10",
    category: "Manicure Supplies",
    location: "retail",
    quantity: 28,
    minQuantity: 20,
    unit: "sets",
    cost: 5.5,
    retailPrice: 14.99,
    supplier: "Beauty Tools Co",
    notes: "Set of 5 different grits",
    lastRestocked: "2024-11-11T13:00:00Z",
  },
  {
    id: "stock_25",
    name: "Eye Cream - Anti-Aging",
    sku: "EC-AAG-15",
    category: "Skincare",
    location: "retail",
    quantity: 13,
    minQuantity: 10,
    unit: "tubes",
    cost: 18.0,
    retailPrice: 44.99,
    supplier: "Green Beauty Co",
    notes: "Retinol formula",
    lastRestocked: "2024-11-10T09:00:00Z",
  },
];
