apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: studio-s

resources:
- hpa.yaml
- ../../base

replicas:
- count: 2
  name: auth
- count: 2
  name: backend
- count: 2
  name: gateway
- count: 2
  name: frontend
- count: 1
  name: google-contacts
- count: 1
  name: notification-api
- count: 2
  name: temporal-worker
- count: 1
  name: temporal
- count: 1
  name: temporal-ui

images:
- name: Maas92/studio-s-api-proxy-server
  newName: Maas92/studio-s-api-proxy-server
  newTag: v4f4cedd2390f4672454c716d7adee0a1cc5d8c5e
- name: Maas92/studio-s-auth
  newName: Maas92/studio-s-auth
  newTag: v4f4cedd2390f4672454c716d7adee0a1cc5d8c5e
- name: Maas92/studio-s-backend
  newName: Maas92/studio-s-backend
  newTag: v4f4cedd2390f4672454c716d7adee0a1cc5d8c5e
- name: Maas92/studio-s-frontend
  newName: Maas92/studio-s-frontend
  newTag: v4f4cedd2390f4672454c716d7adee0a1cc5d8c5e
- name: ghcr.io/maas92/studio-s-api-proxy-server
  newTag: latest
- name: ghcr.io/maas92/studio-s-auth
  newTag: latest
- name: ghcr.io/maas92/studio-s-backend
  newTag: latest
- name: ghcr.io/maas92/studio-s-frontend
  newTag: latest
- name: ghcr.io/maas92/studio-s-google-contacts
  newTag: latest
- name: ghcr.io/maas92/studio-s-whatsapp-api
  newTag: latest
- name: ghcr.io/maas92/studio-s-whatsapp-worker
  newTag: latest

resources:
- hpa.yaml
- ../../base

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
    spec:
      template:
        spec:
          containers:
          - name: backend
            resources:
              requests:
                memory: "512Mi"
                cpu: "400m"
              limits:
                memory: "1Gi"
                cpu: "800m"
  target:
    kind: Deployment
    name: backend
