import type { StaffMember } from "./api";

export const mockStaff: StaffMember[] = [
  {
    id: "staff_1",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@spa.com",
    phone: "+1 (555) 201-3001",
    role: "Senior Massage Therapist",
    specializations: ["Deep Tissue", "Hot Stone", "Sports Massage"],
    status: "active",
    hireDate: "2020-03-15T00:00:00Z",
    bio: "Sarah has over 10 years of experience in therapeutic massage. She specializes in deep tissue work and has helped numerous clients with chronic pain management.",
    certifications: [
      "Licensed Massage Therapist",
      "Certified Sports Massage Therapist",
      "Hot Stone Therapy Certification",
    ],
    performance: {
      staffId: "staff_1",
      period: "2024-11",
      appointmentsCompleted: 87,
      appointmentsCancelled: 3,
      totalRevenue: 8750,
      averageRating: 4.8,
      totalHoursWorked: 168,
      utilizationRate: 85,
      clientRetentionRate: 78,
      noShowRate: 3.4,
    },
  },
  {
    id: "staff_2",
    name: "Michael Chen",
    email: "michael.chen@spa.com",
    phone: "+1 (555) 202-3002",
    role: "Esthetician",
    specializations: ["Facials", "Chemical Peels", "Microdermabrasion"],
    status: "active",
    hireDate: "2021-06-01T00:00:00Z",
    bio: "Michael is passionate about skincare and helping clients achieve their best skin. He stays current with the latest treatments and techniques in the industry.",
    certifications: [
      "Licensed Esthetician",
      "Advanced Chemical Peel Certification",
    ],
    performance: {
      staffId: "staff_2",
      period: "2024-11",
      appointmentsCompleted: 65,
      appointmentsCancelled: 5,
      totalRevenue: 6890,
      averageRating: 4.9,
      totalHoursWorked: 160,
      utilizationRate: 78,
      clientRetentionRate: 82,
      noShowRate: 7.1,
    },
  },
  {
    id: "staff_3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@spa.com",
    phone: "+1 (555) 203-3003",
    role: "Aromatherapy Specialist",
    specializations: ["Aromatherapy", "Relaxation Massage", "Prenatal Massage"],
    status: "active",
    hireDate: "2019-09-20T00:00:00Z",
    bio: "Emily brings a holistic approach to wellness through aromatherapy and massage. She creates custom essential oil blends for each client's unique needs.",
    certifications: [
      "Licensed Massage Therapist",
      "Certified Aromatherapist",
      "Prenatal Massage Certification",
    ],
    performance: {
      staffId: "staff_3",
      period: "2024-11",
      appointmentsCompleted: 72,
      appointmentsCancelled: 2,
      totalRevenue: 7560,
      averageRating: 4.7,
      totalHoursWorked: 152,
      utilizationRate: 92,
      clientRetentionRate: 85,
      noShowRate: 2.7,
    },
  },
  {
    id: "staff_4",
    name: "James Patterson",
    email: "james.patterson@spa.com",
    phone: "+1 (555) 204-3004",
    role: "Massage Therapist",
    specializations: [
      "Swedish Massage",
      "Reflexology",
      "Trigger Point Therapy",
    ],
    status: "active",
    hireDate: "2022-01-10T00:00:00Z",
    bio: "James focuses on relaxation and stress relief through Swedish massage techniques. His calm demeanor helps clients fully relax during treatments.",
    certifications: ["Licensed Massage Therapist", "Reflexology Certification"],
    performance: {
      staffId: "staff_4",
      period: "2024-11",
      appointmentsCompleted: 58,
      appointmentsCancelled: 8,
      totalRevenue: 5220,
      averageRating: 4.5,
      totalHoursWorked: 144,
      utilizationRate: 65,
      clientRetentionRate: 68,
      noShowRate: 12.1,
    },
  },
  {
    id: "staff_5",
    name: "Lisa Thompson",
    email: "lisa.thompson@spa.com",
    phone: "+1 (555) 205-3005",
    role: "Spa Manager",
    specializations: ["Operations", "Customer Service", "Staff Training"],
    status: "active",
    hireDate: "2018-05-01T00:00:00Z",
    bio: "Lisa oversees daily spa operations and ensures every guest has an exceptional experience. She has a background in hospitality management and a passion for wellness.",
    certifications: [
      "Spa Management Certification",
      "Hospitality Management Degree",
    ],
  },
  {
    id: "staff_6",
    name: "David Kim",
    email: "david.kim@spa.com",
    phone: "+1 (555) 206-3006",
    role: "Massage Therapist",
    specializations: ["Thai Massage", "Shiatsu", "Acupressure"],
    status: "on_leave",
    hireDate: "2021-03-15T00:00:00Z",
    bio: "David specializes in Eastern massage techniques. Currently on parental leave and will return next month.",
    certifications: [
      "Licensed Massage Therapist",
      "Thai Massage Certification",
      "Shiatsu Practitioner",
    ],
  },
  {
    id: "staff_7",
    name: "Amanda Foster",
    email: "amanda.foster@spa.com",
    phone: "+1 (555) 207-3007",
    role: "Nail Technician",
    specializations: ["Manicures", "Pedicures", "Gel Polish", "Nail Art"],
    status: "active",
    hireDate: "2022-08-01T00:00:00Z",
    bio: "Amanda is creative and detail-oriented, offering both classic and trendy nail services. She stays up-to-date with the latest nail art techniques.",
    certifications: ["Licensed Nail Technician", "Gel Application Specialist"],
    performance: {
      staffId: "staff_7",
      period: "2024-11",
      appointmentsCompleted: 94,
      appointmentsCancelled: 4,
      totalRevenue: 4230,
      averageRating: 4.6,
      totalHoursWorked: 156,
      utilizationRate: 88,
      clientRetentionRate: 75,
      noShowRate: 4.1,
    },
  },
  {
    id: "staff_8",
    name: "Robert Martinez",
    email: "robert.martinez@spa.com",
    phone: "+1 (555) 208-3008",
    role: "Physical Therapist",
    specializations: [
      "Rehabilitation",
      "Sports Injuries",
      "Therapeutic Exercise",
    ],
    status: "active",
    hireDate: "2020-11-01T00:00:00Z",
    bio: "Robert works with clients recovering from injuries and those seeking to improve their physical wellness. He creates personalized treatment plans for optimal results.",
    certifications: [
      "Licensed Physical Therapist",
      "Sports Rehabilitation Specialist",
      "Certified Strength Coach",
    ],
    performance: {
      staffId: "staff_8",
      period: "2024-11",
      appointmentsCompleted: 48,
      appointmentsCancelled: 6,
      totalRevenue: 7200,
      averageRating: 4.9,
      totalHoursWorked: 140,
      utilizationRate: 72,
      clientRetentionRate: 88,
      noShowRate: 11.1,
    },
  },
  {
    id: "staff_9",
    name: "Jennifer Lee",
    email: "jennifer.lee@spa.com",
    phone: "+1 (555) 209-3009",
    role: "Yoga Instructor",
    specializations: ["Vinyasa Yoga", "Restorative Yoga", "Meditation"],
    status: "active",
    hireDate: "2021-04-15T00:00:00Z",
    bio: "Jennifer teaches both energizing and restorative yoga classes. She believes in the mind-body connection and incorporates mindfulness into all her sessions.",
    certifications: [
      "RYT-500 Yoga Certification",
      "Meditation Teacher Training",
    ],
    performance: {
      staffId: "staff_9",
      period: "2024-11",
      appointmentsCompleted: 112,
      appointmentsCancelled: 12,
      totalRevenue: 3920,
      averageRating: 4.8,
      totalHoursWorked: 132,
      utilizationRate: 95,
      clientRetentionRate: 90,
      noShowRate: 9.7,
    },
  },
  {
    id: "staff_10",
    name: "Christopher Brown",
    email: "chris.brown@spa.com",
    phone: "+1 (555) 210-3010",
    role: "Receptionist",
    specializations: ["Customer Service", "Scheduling", "Retail Sales"],
    status: "active",
    hireDate: "2023-02-01T00:00:00Z",
    bio: "Christopher is the friendly face that greets all our guests. He ensures smooth operations at the front desk and helps clients with bookings and retail purchases.",
    certifications: ["Customer Service Excellence Training"],
  },
];
