apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: studio-s

resources:
  - ../../base

namePrefix: dev-

replicas:
  - name: auth
    count: 1
  - name: backend
    count: 1
  - name: gateway
    count: 1
  - name: frontend
    count: 1
  - name: google-contacts
    count: 1
  - name: notification-api
    count: 1
  - name: temporal-worker
    count: 1
  - name: temporal
    count: 1
  - name: temporal-ui
    count: 1

images:
  - name: ghcr.io/maas92/studio-s-auth
    newTag: dev-latest
  - name: ghcr.io/maas92/studio-s-backend
    newTag: dev-latest
  - name: ghcr.io/maas92/studio-s-api-proxy-server
    newTag: dev-latest
  - name: ghcr.io/maas92/studio-s-frontend
    newTag: dev-latest
  - name: ghcr.io/maas92/studio-s-google-contacts
    newTag: dev-latest
  - name: ghcr.io/maas92/studio-s-whatsapp-api
    newTag: dev-latest
  - name: ghcr.io/maas92/studio-s-whatsapp-worker
    newTag: dev-latest
