apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: studio-s

bases:
  - ../../base

namePrefix: staging-

replicas:
  - name: auth
    count: 2
  - name: backend
    count: 2
  - name: gateway
    count: 2
  - name: frontend
    count: 2

images:
  - name: ghcr.io/Maas92/studio-s-auth
    newTag: staging-latest
  - name: ghcr.io/Maas92/studio-s-backend
    newTag: staging-latest
  - name: ghcr.io/Maas92/studio-s-gateway
    newTag: staging-latest
  - name: ghcr.io/Maas92/studio-s-frontend
    newTag: staging-latest

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info
